language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- iojs
- iojs-v1.0.4
script:
- echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}"
- npm run lint
- npm run cover
after_success:
- npm run coveralls
- |
    test ${TRAVIS_PULL_REQUEST} == "false" && \
    test ${TRAVIS_BRANCH} == "feature/yuidoc" && \
    test "${TRAVIS_BUILD_NUMBER}.1" === "${TRAVIS_JOB_NUMBER}" && \
    npm run document && \
    npm run publishdocs
env:
  global:
  - secure: C6Tfjv34GSMGKDRQR79L8t9BY030CuhzWCaTfrUQob7DPNoWD57FUIKFAZwomdO01nKAujUua+VkaYnyRvxQ3HLqb59KVlVrm5T0bJKcKlxa3Y8IBHoA6Rh0fYiJhSz5PK1WSsSiauhR2cZzxBk4ObCyHdMfwH2tufDahQqsUSY=
  - GH_USER: bguiz
  - GH_REPO: plugin-registry
  - GIT_USER: Travis CI Git User
  - GIT_EMAIL: travis.ci.git.user@bguiz.com
